{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Load Libraries"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import torch\n",
    "import torchvision\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "import torch.optim as optim\n",
    "import torch.utils.data as utils\n",
    "\n",
    "from functools import partial\n",
    "from ray import tune\n",
    "from ray.tune import CLIReporter\n",
    "from ray.tune.schedulers import ASHAScheduler\n",
    "\n",
    "import os\n",
    "import time\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of available CPU's: 12\n"
     ]
    }
   ],
   "source": [
    "# Show number of avlaible CPU threads\n",
    "# With mulithreading this number is twice the number of physical cores\n",
    "cpu_av = os.cpu_count()\n",
    "print(\"Number of available CPU's: {}\".format(cpu_av))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Set the number CPUS that should be used per trial and dataloader\n",
    "# If set to 1 number of cucurrent training networking is equal to this number\n",
    "# In case of training with GPU this will be limited to number of models training simultaneously on GPU\n",
    "# So number of CPU threads for each trial can be increased \n",
    "cpus_per_trial = 1\n",
    "gpus_per_trial = 0"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Load data from files"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Needs reworking opening and closing the file too many times with multithreading\n",
    "class ClusterDataset_Partial(utils.Dataset):\n",
    "    \"\"\"Cluster dataset.\"\"\"\n",
    "\n",
    "    def __init__(self, npz_file, arrsize=20):\n",
    "        \"\"\"\n",
    "        Args:\n",
    "            npz_file (string): Path to the npz file.\n",
    "        \"\"\"\n",
    "        self.data = np.load(npz_file, allow_pickle=True)\n",
    "        self.arrsize = arrsize\n",
    "        \n",
    "\n",
    "    def __len__(self):\n",
    "        return self.data[\"Size\"]\n",
    "    \n",
    "    def __ReconstructCluster(self, ncell, modnum, row, col, cdata):\n",
    "        _row = row.copy()\n",
    "        _col = col.copy()       \n",
    "        if not np.all( modnum[0] == modnum[:ncell]):\n",
    "            ModNumDif = modnum - np.min(modnum[:ncell])\n",
    "            mask = np.where(ModNumDif == 1)\n",
    "            _col[mask] += 48\n",
    "            mask = np.where(ModNumDif == 2)\n",
    "            _row[mask] += 24\n",
    "            mask = np.where(ModNumDif == 3)\n",
    "            _row[mask] += 24\n",
    "            _col[mask] += 48\n",
    "        \n",
    "        arr = np.zeros(( self.arrsize, self.arrsize ), dtype=np.float32)\n",
    "  \n",
    "        col_min = np.min(_col[:ncell])\n",
    "        row_min = np.min(_row[:ncell])\n",
    "        width = np.max(_col[:ncell]) - col_min\n",
    "        height = np.max(_row[:ncell]) - row_min\n",
    "        offset_h = int((self.arrsize-height)/2)\n",
    "        offset_w = int((self.arrsize-width)/2)\n",
    "        \n",
    "        for i in range(ncell):\n",
    "            arr[ _row[i] - row_min + offset_h, _col[i] - col_min + offset_w ] = cdata[i]\n",
    "\n",
    "        return arr\n",
    "    \n",
    "    def __GetClusters(self, ncell, modnum, row, col, energy, timing):\n",
    "        \n",
    "        cluster_e = self.__ReconstructCluster(ncell, modnum, row, col, energy)\n",
    "        cluster_t = self.__ReconstructCluster(ncell, modnum, row, col, timing)\n",
    "\n",
    "        return np.stack([cluster_e, cluster_t], axis=1)\n",
    "    \n",
    "    def __ChangePID(self, PID):\n",
    "        if (PID != 111) & (PID != 221):\n",
    "            PID = np.int16(0)\n",
    "        if PID == 111:\n",
    "            PID = np.int16(1)\n",
    "        if PID == 221:\n",
    "            PID = np.int16(2)\n",
    "        return PID\n",
    "    \n",
    "    def __ToTensor(self, sample):       \n",
    "        for key in sample.keys(): \n",
    "            if sample[key].dtype == np.bool_:\n",
    "                sample[key] = bool(sample[key])\n",
    "            _temp = torch.as_tensor(sample[key])\n",
    "            sample[key] = _temp.view(-1,1)\n",
    "            \n",
    "        return sample\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        if torch.is_tensor(idx):\n",
    "            idx = idx.tolist()\n",
    "        \n",
    "        ClusterN = self.data['ClusterN'][idx]\n",
    "        Cluster = self.data['Cluster'][idx]\n",
    "        ClusterTiming = self.data['ClusterTiming'][idx]\n",
    "        ClusterType = self.data['ClusterType'][idx]\n",
    "        ClusterE = self.data['ClusterE'][idx]\n",
    "        ClusterPt = self.data['ClusterPt'][idx]\n",
    "        ClusterModuleNumber = self.data['ClusterModuleNumber'][idx]\n",
    "        ClusterCol = self.data['ClusterCol'][idx]\n",
    "        ClusterRow = self.data['ClusterRow'][idx]\n",
    "        ClusterM02 = self.data['ClusterM02'][idx]\n",
    "        ClusterM20 = self.data['ClusterM20'][idx]\n",
    "        ClusterDistFromVert = self.data['ClusterDistFromVert'][idx]\n",
    "        PartE = self.data['PartE'][idx]\n",
    "        PartPt = self.data['PartPt'][idx]\n",
    "        PartEta = self.data['PartEta'][idx]\n",
    "        PartPhi = self.data['PartPhi'][idx]\n",
    "        PartIsPrimary = self.data['PartIsPrimary'][idx]\n",
    "        PartPID = self.data['PartPID'][idx]\n",
    "\n",
    "        \n",
    "        PartPID = self.__ChangePID(PartPID)\n",
    "        \n",
    "        img = self.__GetClusters(ClusterN, ClusterModuleNumber, ClusterRow, ClusterCol, Cluster, ClusterTiming)\n",
    "        img = torch.from_numpy(img)\n",
    "        \n",
    "        features = { \"ClusterType\" : ClusterType, \"ClusterE\" : ClusterE, \"ClusterPt\" : ClusterPt\n",
    "                    , \"ClusterM02\" : ClusterM02, \"ClusterM20\" : ClusterM20 , \"ClusterDistFromVert\" : ClusterDistFromVert}\n",
    "        labels = { \"PartE\" : PartE, \"PartPt\" : PartPt, \"PartEta\" : PartEta, \"PartPhi\" : PartPhi\n",
    "                  , \"PartIsPrimary\" : PartIsPrimary, \"PartPID\" : PartPID }\n",
    "        \n",
    "        features = self.__ToTensor(features)\n",
    "        labels = self.__ToTensor(labels)\n",
    "        \n",
    "        return img, features, labels"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "class ClusterDataset_Full(utils.Dataset):\n",
    "    \"\"\"Cluster dataset.\"\"\"\n",
    "\n",
    "    def __init__(self, npz_file, arrsize=20):\n",
    "        \"\"\"\n",
    "        Args:\n",
    "            npz_file (string): Path to the npz file.\n",
    "        \"\"\"\n",
    "        self.data = np.load(npz_file, allow_pickle=True)\n",
    "        self.arrsize = arrsize\n",
    "        self.ClusterN = self.data['ClusterN']\n",
    "        self.Cluster = self.data['Cluster']\n",
    "        self.ClusterTiming = self.data['ClusterTiming']\n",
    "        self.ClusterType = self.data['ClusterType']\n",
    "        self.ClusterE = self.data['ClusterE']\n",
    "        self.ClusterPt = self.data['ClusterPt']\n",
    "        self.ClusterModuleNumber = self.data['ClusterModuleNumber']\n",
    "        self.ClusterCol = self.data['ClusterCol']\n",
    "        self.ClusterRow = self.data['ClusterRow']\n",
    "        self.ClusterM02 = self.data['ClusterM02']\n",
    "        self.ClusterM20 = self.data['ClusterM20']\n",
    "        self.ClusterDistFromVert = self.data['ClusterDistFromVert']\n",
    "        self.PartE = self.data['PartE']\n",
    "        self.PartPt = self.data['PartPt']\n",
    "        self.PartEta = self.data['PartEta']\n",
    "        self.PartPhi = self.data['PartPhi']\n",
    "        self.PartIsPrimary = self.data['PartIsPrimary']\n",
    "        self.PartPID = self.data['PartPID']\n",
    "\n",
    "    def __len__(self):\n",
    "        return self.data[\"Size\"]\n",
    "    \n",
    "    def __ReconstructCluster(self, ncell, modnum, row, col, cdata):\n",
    "        _row = row.copy()\n",
    "        _col = col.copy()       \n",
    "        if not np.all( modnum[0] == modnum[:ncell]):\n",
    "            ModNumDif = modnum - np.min(modnum[:ncell])\n",
    "            mask = np.where(ModNumDif == 1)\n",
    "            _col[mask] += 48\n",
    "            mask = np.where(ModNumDif == 2)\n",
    "            _row[mask] += 24\n",
    "            mask = np.where(ModNumDif == 3)\n",
    "            _row[mask] += 24\n",
    "            _col[mask] += 48\n",
    "        \n",
    "        arr = np.zeros(( self.arrsize, self.arrsize ), dtype=np.float32)\n",
    "  \n",
    "        col_min = np.min(_col[:ncell])\n",
    "        row_min = np.min(_row[:ncell])\n",
    "        width = np.max(_col[:ncell]) - col_min\n",
    "        height = np.max(_row[:ncell]) - row_min\n",
    "        offset_h = int((self.arrsize-height)/2)\n",
    "        offset_w = int((self.arrsize-width)/2)\n",
    "        \n",
    "        for i in range(ncell):\n",
    "            arr[ _row[i] - row_min + offset_h, _col[i] - col_min + offset_w ] = cdata[i]\n",
    "\n",
    "        return arr\n",
    "    \n",
    "    def __GetClusters(self, ncell, modnum, row, col, energy, timing):       \n",
    "        cluster_e = self.__ReconstructCluster(ncell, modnum, row, col, energy)\n",
    "        cluster_t = self.__ReconstructCluster(ncell, modnum, row, col, timing)\n",
    "\n",
    "        return np.stack([cluster_e, cluster_t], axis=1)\n",
    "    \n",
    "    def __ChangePID(self, PID):\n",
    "        if (PID != 111) & (PID != 221):\n",
    "            PID = np.int16(0)\n",
    "        if PID == 111:\n",
    "            PID = np.int16(1)\n",
    "        if PID == 221:\n",
    "            PID = np.int16(2)\n",
    "        return PID\n",
    "    \n",
    "    def __ToTensor(self, sample):       \n",
    "        for key in sample.keys(): \n",
    "            if sample[key].dtype == np.bool_:\n",
    "                sample[key] = bool(sample[key])\n",
    "            _temp = torch.as_tensor(sample[key])\n",
    "            sample[key] = _temp.view(-1,1)\n",
    "            \n",
    "        return sample\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        if torch.is_tensor(idx):\n",
    "            idx = idx.tolist()\n",
    "        \n",
    "        ClusterN = self.ClusterN[idx]\n",
    "        Cluster = self.Cluster[idx]\n",
    "        ClusterTiming = self.ClusterTiming[idx]\n",
    "        ClusterType = self.ClusterType[idx]\n",
    "        ClusterE = self.ClusterE[idx]\n",
    "        ClusterPt = self.ClusterPt[idx]\n",
    "        ClusterModuleNumber = self.ClusterModuleNumber[idx]\n",
    "        ClusterCol = self.ClusterCol[idx]\n",
    "        ClusterRow = self.ClusterRow[idx]\n",
    "        ClusterM02 = self.ClusterM02[idx]\n",
    "        ClusterM20 = self.ClusterM20[idx]\n",
    "        ClusterDistFromVert = self.ClusterDistFromVert[idx]\n",
    "        PartE = self.PartE[idx]\n",
    "        PartPt = self.PartPt[idx]\n",
    "        PartEta = self.PartEta[idx]\n",
    "        PartPhi = self.PartPhi[idx]\n",
    "        PartIsPrimary = self.PartIsPrimary[idx]\n",
    "        PartPID = self.PartPID[idx]\n",
    "        \n",
    "        PartPID = self.__ChangePID(PartPID)\n",
    "        \n",
    "        img = self.__GetClusters(ClusterN, ClusterModuleNumber, ClusterRow, ClusterCol, Cluster, ClusterTiming)\n",
    "        img = torch.from_numpy(img)\n",
    "        \n",
    "        features = { \"ClusterType\" : ClusterType, \"ClusterE\" : ClusterE, \"ClusterPt\" : ClusterPt\n",
    "                    , \"ClusterM02\" : ClusterM02, \"ClusterM20\" : ClusterM20 , \"ClusterDist\" : ClusterDistFromVert}\n",
    "        labels = { \"PartE\" : PartE, \"PartPt\" : PartPt, \"PartEta\" : PartEta, \"PartPhi\" : PartPhi\n",
    "                  , \"PartIsPrimary\" : PartIsPrimary, \"PartPID\" : PartPID }\n",
    "        \n",
    "        features = self.__ToTensor(features)\n",
    "        labels = self.__ToTensor(labels)\n",
    "        \n",
    "        return img, features, labels"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "test = ClusterDataset_Full('Data/data_train.npz')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "dl = utils.DataLoader(test, batch_size=100, shuffle=True, num_workers=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [],
   "source": [
    "for im, features, labels in dl:\n",
    "    break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 123,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([[[11.1069]],\n",
       "\n",
       "        [[ 6.7433]],\n",
       "\n",
       "        [[ 7.0125]],\n",
       "\n",
       "        [[ 7.0163]],\n",
       "\n",
       "        [[ 8.2837]],\n",
       "\n",
       "        [[ 7.5721]],\n",
       "\n",
       "        [[ 6.2261]],\n",
       "\n",
       "        [[ 9.9877]],\n",
       "\n",
       "        [[ 7.0889]],\n",
       "\n",
       "        [[ 9.2565]],\n",
       "\n",
       "        [[ 9.1229]],\n",
       "\n",
       "        [[ 6.2986]],\n",
       "\n",
       "        [[ 6.5444]],\n",
       "\n",
       "        [[11.2940]],\n",
       "\n",
       "        [[ 6.4508]],\n",
       "\n",
       "        [[ 6.9114]],\n",
       "\n",
       "        [[ 6.8362]],\n",
       "\n",
       "        [[ 6.7787]],\n",
       "\n",
       "        [[ 6.5188]],\n",
       "\n",
       "        [[12.3032]],\n",
       "\n",
       "        [[ 6.3617]],\n",
       "\n",
       "        [[ 6.0942]],\n",
       "\n",
       "        [[ 6.6236]],\n",
       "\n",
       "        [[ 6.3706]],\n",
       "\n",
       "        [[11.8061]],\n",
       "\n",
       "        [[ 6.7642]],\n",
       "\n",
       "        [[10.0031]],\n",
       "\n",
       "        [[ 6.3611]],\n",
       "\n",
       "        [[ 6.4638]],\n",
       "\n",
       "        [[14.6166]],\n",
       "\n",
       "        [[11.3357]],\n",
       "\n",
       "        [[ 6.5265]],\n",
       "\n",
       "        [[ 7.4878]],\n",
       "\n",
       "        [[ 8.0202]],\n",
       "\n",
       "        [[ 6.8397]],\n",
       "\n",
       "        [[ 7.8281]],\n",
       "\n",
       "        [[ 6.7342]],\n",
       "\n",
       "        [[ 7.5886]],\n",
       "\n",
       "        [[ 6.6623]],\n",
       "\n",
       "        [[11.0091]],\n",
       "\n",
       "        [[ 7.3196]],\n",
       "\n",
       "        [[ 7.5930]],\n",
       "\n",
       "        [[ 9.7992]],\n",
       "\n",
       "        [[ 8.8422]],\n",
       "\n",
       "        [[ 7.7185]],\n",
       "\n",
       "        [[ 6.5373]],\n",
       "\n",
       "        [[ 6.3840]],\n",
       "\n",
       "        [[ 6.6040]],\n",
       "\n",
       "        [[ 7.1177]],\n",
       "\n",
       "        [[ 6.8025]],\n",
       "\n",
       "        [[ 6.1976]],\n",
       "\n",
       "        [[ 7.0046]],\n",
       "\n",
       "        [[19.7165]],\n",
       "\n",
       "        [[ 6.3647]],\n",
       "\n",
       "        [[ 7.6653]],\n",
       "\n",
       "        [[ 6.0269]],\n",
       "\n",
       "        [[12.5002]],\n",
       "\n",
       "        [[ 6.9122]],\n",
       "\n",
       "        [[18.2670]],\n",
       "\n",
       "        [[19.6293]],\n",
       "\n",
       "        [[ 9.5384]],\n",
       "\n",
       "        [[ 8.0186]],\n",
       "\n",
       "        [[14.3325]],\n",
       "\n",
       "        [[14.0624]],\n",
       "\n",
       "        [[ 8.6353]],\n",
       "\n",
       "        [[ 8.1371]],\n",
       "\n",
       "        [[ 6.4270]],\n",
       "\n",
       "        [[ 6.0796]],\n",
       "\n",
       "        [[ 9.2361]],\n",
       "\n",
       "        [[11.4667]],\n",
       "\n",
       "        [[ 6.7610]],\n",
       "\n",
       "        [[40.1406]],\n",
       "\n",
       "        [[ 6.3634]],\n",
       "\n",
       "        [[ 6.4508]],\n",
       "\n",
       "        [[ 7.7734]],\n",
       "\n",
       "        [[ 6.9508]],\n",
       "\n",
       "        [[ 6.1951]],\n",
       "\n",
       "        [[ 6.1975]],\n",
       "\n",
       "        [[ 6.2939]],\n",
       "\n",
       "        [[ 8.5536]],\n",
       "\n",
       "        [[ 6.3369]],\n",
       "\n",
       "        [[ 7.8687]],\n",
       "\n",
       "        [[ 6.9078]],\n",
       "\n",
       "        [[ 6.0997]],\n",
       "\n",
       "        [[ 7.2665]],\n",
       "\n",
       "        [[ 6.2403]],\n",
       "\n",
       "        [[ 6.2181]],\n",
       "\n",
       "        [[10.7227]],\n",
       "\n",
       "        [[ 7.8632]],\n",
       "\n",
       "        [[11.6477]],\n",
       "\n",
       "        [[ 8.5397]],\n",
       "\n",
       "        [[ 7.0960]],\n",
       "\n",
       "        [[10.6223]],\n",
       "\n",
       "        [[ 6.7415]],\n",
       "\n",
       "        [[ 8.2215]],\n",
       "\n",
       "        [[ 6.0934]],\n",
       "\n",
       "        [[19.2853]],\n",
       "\n",
       "        [[13.2758]],\n",
       "\n",
       "        [[ 6.7745]],\n",
       "\n",
       "        [[ 8.4283]]])"
      ]
     },
     "execution_count": 123,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "labels[\"PartE\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Path to data\n",
    "train_path = 'Data/data_train.npz'\n",
    "test_path = 'Data/data_test.npz'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "train_data = np.load(train_path, allow_pickle=True)\n",
    "test_data = np.load(test_path, allow_pickle=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "184\n"
     ]
    }
   ],
   "source": [
    "test = train_data[\"Size\"]\n",
    "print(test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "ClusterN_train = train_data['ClusterN']\n",
    "Cluster_train = train_data['Cluster']\n",
    "ClusterTiming_train = train_data['ClusterTiming']\n",
    "ClusterType_train = train_data['ClusterType']\n",
    "ClusterE_train = train_data['ClusterE']\n",
    "ClusterPt_train = train_data['ClusterPt']\n",
    "ClusterModuleNumber_train = train_data['ClusterModuleNumber']\n",
    "ClusterCol_train = train_data['ClusterCol']\n",
    "ClusterRow_train = train_data['ClusterRow']\n",
    "ClusterM02_train = train_data['ClusterM02']\n",
    "ClusterM20_train = train_data['ClusterM20']\n",
    "ClusterDistFromVert_train = train_data['ClusterDistFromVert']\n",
    "PartE_train = train_data['PartE']\n",
    "PartPt_train = train_data['PartPt']\n",
    "PartEta_train = train_data['PartEta']\n",
    "PartPhi_train = train_data['PartPhi']\n",
    "PartIsPrimary_train = train_data['PartIsPrimary']\n",
    "PartPID_train = train_data['PartPID']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "ClusterN_test = test_data['ClusterN']\n",
    "Cluster_test = test_data['Cluster']\n",
    "ClusterTiming_test = test_data['ClusterTiming']\n",
    "ClusterType_test = test_data['ClusterType']\n",
    "ClusterE_test = test_data['ClusterE']\n",
    "ClusterPt_test = test_data['ClusterPt']\n",
    "ClusterModuleNumber_test = test_data['ClusterModuleNumber']\n",
    "ClusterCol_test = test_data['ClusterCol']\n",
    "ClusterRow_test = test_data['ClusterRow']\n",
    "ClusterM02_test = test_data['ClusterM02']\n",
    "ClusterM20_test = test_data['ClusterM20']\n",
    "ClusterDistFromVert_test = test_data['ClusterDistFromVert']\n",
    "PartE_test = test_data['PartE']\n",
    "PartPt_test = test_data['PartPt']\n",
    "PartEta_test = test_data['PartEta']\n",
    "PartPhi_test = test_data['PartPhi']\n",
    "PartIsPrimary_test = test_data['PartIsPrimary']\n",
    "PartPID_test = test_data['PartPID']"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Temporary change for PID into three categories"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "def change_pid(arr):\n",
    "    arr[np.nonzero((arr != 111) & (arr != 221))] = 0\n",
    "    arr[arr == 111] = 1\n",
    "    arr[arr == 221] = 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "change_pid(PartPID_test)\n",
    "change_pid(PartPID_train)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Reshape the arrays into [size, 1] for usage with ptorch\n",
    "\n",
    "For linear layers input is expected as [batch_size, num_features] so no need to reshape the existing arrays like Cluster\n",
    "\n",
    "reconstrcuted clusters later will have to have dim [batch_size, channel, height, width] as input for conv2d-layers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "maxClusN_train = np.max(ClusterN_train)\n",
    "maxClusN_test = np.max(ClusterN_test)\n",
    "maxClusN = np.max([maxClusN_test, maxClusN_train])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "ClusterN_train = ClusterN_train.reshape((ClusterN_train.size, 1))\n",
    "#Cluster_train = Cluster_train.reshape((ClusterE_train.size, maxClusN))\n",
    "ClusterType_train = ClusterType_train.reshape((ClusterType_train.size, 1))\n",
    "ClusterE_train = ClusterE_train.reshape((ClusterE_train.size, 1))\n",
    "ClusterPt_train = ClusterPt_train.reshape((ClusterPt_train.size, 1))\n",
    "#ClusterModuleNumber_train = ClusterModuleNumber_train.reshape((ClusterModuleNumber_train.size, maxClusN))\n",
    "#ClusterRow_train = ClusterRow_train.reshape((ClusterRow_train.size, maxClusN))\n",
    "#ClusterCol_train = ClusterCol_train.reshape((ClusterCol_train.size, maxClusN))\n",
    "ClusterM02_train = ClusterM02_train.reshape((ClusterM02_train.size, 1))\n",
    "ClusterM20_train = ClusterM20_train.reshape((ClusterM20_train.size, 1))\n",
    "ClusterDistFromVert_train = ClusterDistFromVert_train.reshape((ClusterDistFromVert_train.size, 1))\n",
    "PartE_train = PartE_train.reshape((PartE_train.size, 1))\n",
    "PartPt_train = PartPt_train.reshape((PartPt_train.size, 1))\n",
    "PartEta_train = PartEta_train.reshape((PartEta_train.size, 1))\n",
    "PartPhi_train = PartPhi_train.reshape((PartPhi_train.size, 1))\n",
    "PartIsPrimary_train = PartIsPrimary_train.reshape((PartIsPrimary_train.size, 1))\n",
    "PartPID_train = PartPID_train.reshape((PartPID_train.size, 1))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "ClusterN_test = ClusterN_test.reshape((ClusterN_test.size, 1))\n",
    "#Cluster_test = Cluster_test.reshape((ClusterE_test.size, maxClusN))\n",
    "ClusterType_test = ClusterType_test.reshape((ClusterType_test.size, 1))\n",
    "ClusterE_test = ClusterE_test.reshape((ClusterE_test.size, 1))\n",
    "ClusterPt_test = ClusterPt_test.reshape((ClusterPt_test.size, 1))\n",
    "#ClusterModuleNumber_test = ClusterModuleNumber_test.reshape((ClusterModuleNumber_test.size, maxClusN))\n",
    "#ClusterRow_test = ClusterRow_test.reshape((ClusterRow_test.size, maxClusN))\n",
    "#ClusterCol_test = ClusterCol_test.reshape((ClusterCol_test.size, maxClusN))\n",
    "ClusterM02_test = ClusterM02_test.reshape((ClusterM02_test.size, 1))\n",
    "ClusterM20_test = ClusterM20_test.reshape((ClusterM20_test.size, 1))\n",
    "ClusterDistFromVert_test = ClusterDistFromVert_test.reshape((ClusterDistFromVert_test.size, 1))\n",
    "PartE_test = PartE_test.reshape((PartE_test.size, 1))\n",
    "PartPt_test = PartPt_test.reshape((PartPt_test.size, 1))\n",
    "PartEta_test = PartEta_test.reshape((PartEta_test.size, 1))\n",
    "PartPhi_test = PartPhi_test.reshape((PartPhi_test.size, 1))\n",
    "PartIsPrimary_test = PartIsPrimary_test.reshape((PartIsPrimary_test.size, 1))\n",
    "PartPID_test = PartPID_test.reshape((PartPID_test.size, 1))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Load it to pytorch `tensor`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "ClusterN_train = torch.as_tensor(ClusterN_train, dtype=torch.uint8)\n",
    "Cluster_train = torch.as_tensor(Cluster_train, dtype=torch.float32)\n",
    "ClusterTiming_train = torch.as_tensor(ClusterTiming_train, dtype=torch.float32)\n",
    "ClusterType_train = torch.as_tensor(ClusterType_train, dtype=torch.uint8)\n",
    "ClusterE_train = torch.as_tensor(ClusterE_train, dtype=torch.float32)\n",
    "ClusterPt_train = torch.as_tensor(ClusterPt_train, dtype=torch.float32)\n",
    "ClusterModuleNumber_train = torch.as_tensor(ClusterModuleNumber_train, dtype=torch.uint8)\n",
    "ClusterRow_train = torch.as_tensor(ClusterRow_train, dtype=torch.uint8)\n",
    "ClusterCol_train = torch.as_tensor(ClusterCol_train, dtype=torch.uint8)\n",
    "ClusterM02_train = torch.as_tensor(ClusterM02_train, dtype=torch.float32)\n",
    "ClusterM20_train = torch.as_tensor(ClusterM20_train, dtype=torch.float32)\n",
    "ClusterDistFromVert_train = torch.as_tensor(ClusterDistFromVert_train, dtype=torch.float32)\n",
    "PartE_train = torch.as_tensor(PartE_train, dtype=torch.float32)\n",
    "PartPt_train = torch.as_tensor(PartPt_train, dtype=torch.float32)\n",
    "PartEta_train = torch.as_tensor(PartEta_train, dtype=torch.float32)\n",
    "PartPhi_train = torch.as_tensor(PartPhi_train, dtype=torch.float32)\n",
    "PartIsPrimary_train = torch.as_tensor(PartIsPrimary_train, dtype=torch.bool)\n",
    "PartPID_train = torch.as_tensor(PartPID_train, dtype=torch.short)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "ClusterN_test = torch.as_tensor(ClusterN_test, dtype=torch.uint8)\n",
    "Cluster_test = torch.as_tensor(Cluster_test, dtype=torch.float32)\n",
    "ClusterTiming_test = torch.as_tensor(ClusterTiming_test, dtype=torch.float32)\n",
    "ClusterType_test = torch.as_tensor(ClusterType_test, dtype=torch.uint8)\n",
    "ClusterE_test = torch.as_tensor(ClusterE_test, dtype=torch.float32)\n",
    "ClusterPt_test = torch.as_tensor(ClusterPt_test, dtype=torch.float32)\n",
    "ClusterModuleNumber_test = torch.as_tensor(ClusterModuleNumber_test, dtype=torch.uint8)\n",
    "ClusterRow_test = torch.as_tensor(ClusterRow_test, dtype=torch.uint8)\n",
    "ClusterCol_test = torch.as_tensor(ClusterCol_test, dtype=torch.uint8)\n",
    "ClusterM02_test = torch.as_tensor(ClusterM02_test, dtype=torch.float32)\n",
    "ClusterM20_test = torch.as_tensor(ClusterM20_test, dtype=torch.float32)\n",
    "ClusterDistFromVert_test = torch.as_tensor(ClusterDistFromVert_test, dtype=torch.float32)\n",
    "PartE_test = torch.as_tensor(PartE_test, dtype=torch.float32)\n",
    "PartPt_test = torch.as_tensor(PartPt_test, dtype=torch.float32)\n",
    "PartEta_test = torch.as_tensor(PartEta_test, dtype=torch.float32)\n",
    "PartPhi_test = torch.as_tensor(PartPhi_test, dtype=torch.float32)\n",
    "PartIsPrimary_test = torch.as_tensor(PartIsPrimary_test, dtype=torch.bool)\n",
    "PartPID_test = torch.as_tensor(PartPID_test, dtype=torch.short)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Define Functions for DataSet and Dataloader"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_data_train():\n",
    "    dataset_train = utils.TensorDataset( ClusterN_train, Cluster_train, ClusterTiming_train, ClusterType_train\n",
    "                                    , ClusterE_train, ClusterPt_train, ClusterModuleNumber_train\n",
    "                                    , ClusterRow_train, ClusterCol_train, ClusterM02_train, ClusterM20_train\n",
    "                                    , ClusterDistFromVert_train, PartE_train, PartPt_train\n",
    "                                    , PartEta_train, PartPhi_train, PartIsPrimary_train, PartPID_train )\n",
    "    \n",
    "    return dataset_train\n",
    "\n",
    "def load_data_test():\n",
    "    dataset_test = utils.TensorDataset( ClusterN_test, Cluster_test, ClusterTiming_test, ClusterType_test\n",
    "                                   , ClusterE_test, ClusterPt_test, ClusterModuleNumber_test\n",
    "                                   , ClusterRow_test, ClusterCol_test, ClusterM02_test, ClusterM20_test\n",
    "                                   , ClusterDistFromVert_test, PartE_test, PartPt_test\n",
    "                                    , PartEta_test, PartPhi_test, PartIsPrimary_test, PartPID_test )\n",
    "    \n",
    "    return dataset_test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_data_train():\n",
    "    ds_train = ClusterDataset_Full('/home/jhonerma/ML-Notebooks/CNN/Data/data_train.npz')\n",
    "    return ds_train\n",
    "\n",
    "def load_data_test():\n",
    "    ds_test = ClusterDataset_Full('/home/jhonerma/ML-Notebooks/CNN/Data/data_test.npz')\n",
    "    return ds_test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_dataloader(train_ds, val_ds, bs):\n",
    "    return (\n",
    "        utils.DataLoader(train_ds, batch_size=bs, shuffle=True, num_workers=cpus_per_trial),\n",
    "        utils.DataLoader(val_ds, batch_size=bs * 2, shuffle=True, num_workers=cpus_per_trial),\n",
    "    )"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Instance Noise"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# https://arxiv.org/abs/1610.04490\n",
    "INSTANCE_NOISE = False\n",
    "\n",
    "def add_instance_noise(data, std=0.01):\n",
    "    return data + torch.distributions.Normal(0, std).sample(data.shape) #.to(device)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Define the network"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "class CNN(nn.Module):\n",
    "    def __init__(self, l1=100, l2=50, l3=25):\n",
    "        super(CNN, self).__init__()\n",
    "        self.conv1 = nn.Conv2d(1,10, kernel_size=3, padding=2)\n",
    "        self.conv2 = nn.Conv2d(10,10, kernel_size=3,  padding=2)\n",
    "        self.conv3 = nn.Conv2d(10,10, kernel_size=3, padding=0)\n",
    "        self.conv4 = nn.Conv2d(10,5, kernel_size=1, padding=0)\n",
    "        self.conv5 = nn.Conv2d(5,3, kernel_size=1)\n",
    "        self.flatten = nn.Flatten()\n",
    "        self.dense_nn = nn.Sequential(\n",
    "            nn.Linear(4005, l1),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(l1, l1),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(l1, l2),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(l2, l3),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(l3,3),\n",
    "            nn.ReLU()\n",
    "        )\n",
    "        \n",
    "    def forward(self, cluster, clusNumXYEPt):\n",
    "        cluster = F.relu(self.conv1(cluster))\n",
    "        cluster = F.relu(self.conv2(cluster))\n",
    "        cluster = F.relu(self.conv3(cluster))\n",
    "        cluster = F.relu(self.conv3(cluster))\n",
    "        x = self.flatten(cluster)\n",
    "        x = torch.cat([x, clusNumXYEPt], dim=1)\n",
    "        logits = self.dense_nn(x)\n",
    "        return logits"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Function for cluster reconstruction"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "def reconstruct_cluster(ncell, modnum, row, col, data, arrsize=20):\n",
    "    if not torch.all( modnum[0] == modnum[:ncell]):\n",
    "        ModNumDif = modnum - torch.min(modnum[:ncell])\n",
    "        mask = torch.where(ModNumDif == 1)\n",
    "        col[mask] += 48\n",
    "        mask = torch.where(ModNumDif == 2)\n",
    "        row[mask] += 24\n",
    "        mask = torch.where(ModNumDif == 3)\n",
    "        row[mask] += 24\n",
    "        col[mask] += 48\n",
    "\n",
    "    arr = torch.zeros((arrsize,arrsize), dtype=torch.float32)\n",
    "  \n",
    "    col_min = torch.min(col[:ncell])\n",
    "    row_min = torch.min(row[:ncell])\n",
    "    width = torch.max(col[:ncell]) - col_min\n",
    "    height = torch.max(row[:ncell]) - row_min\n",
    "    offset_h = ((arrsize-height)/2).int()\n",
    "    offset_w = ((arrsize-width)/2).int()\n",
    "    \n",
    "    for i in range(ncell):\n",
    "        arr[ row[i] - row_min + offset_h, col[i] - col_min + offset_w ] = data[i]\n",
    "\n",
    "    return arr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_clusters(ncell, modnum, row, col, energy, timing):\n",
    "    \n",
    "    clusters_e = []\n",
    "    clusters_t = []\n",
    "    \n",
    "    for i in range(ClN.shape[0]):\n",
    "        _cluster = reconstruct_cluster(ncell[i], modnum[i], row[i], col[i], energy[i])\n",
    "        clusters_e.append(_cluster)\n",
    "        _cluster = reconstruct_cluster(ncell[i], modnum[i], row[i], col[i], timing[i])\n",
    "        clusters_t.append(_cluster)\n",
    "        \n",
    "    clusters_e = torch.stack(clusters_e)\n",
    "    clusters_t = torch.stack(clusters_t)\n",
    "    #clusters_e = clusters_e.view(-1, 1, 20, 20)\n",
    "    #clusters_t = clusters_t.view(-1, 1, 20, 20)\n",
    "    print(torch.stack([clusters_e,clusters_t], dim=1).shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "dataset_train = load_data_train()\n",
    "    \n",
    "# split trainset in train and validation subsets\n",
    "test_abs = int(len(dataset_train) * 0.8)\n",
    "subset_train, subset_val = utils.random_split(\n",
    "        dataset_train, [test_abs, len(dataset_train) - test_abs])\n",
    "    \n",
    "# get dataloaders \n",
    "dataloader_train, dataloader_val = get_dataloader(subset_train, subset_val, 10)\n",
    "    \n",
    "for data in dataloader_train:\n",
    "    break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "torch.Size([10, 2, 20, 20])\n"
     ]
    }
   ],
   "source": [
    "ClN, Cl, ClT, ClE, ClPt, ClModNum, ClRow, ClCol, ClM02, ClM20, ClDist, PartPID = data[0], data[1], data[2],\\\n",
    "        data[4], data[5], data[6], \\\n",
    "        data[7], data[8], data[9], data[10], \\\n",
    "        data[11], data[17]\n",
    "\n",
    "\n",
    "get_clusters(ClN, ClModNum, ClRow, ClCol, Cl, ClT)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Implement train and validation loop\n",
    "[0: 'ClusterN', 1:'Cluster', 2:'ClusterTiming', 3:'ClusterType', 4:'ClusterE', 5:'ClusterPt', 6:'ClusterModuleNumber', 7:'ClusterRow', 8:'ClusterCol', 9:'ClusterM02', 10:'ClusterM20', 11:'ClusterDistFromVert', 12:'PartE', 13:'PartPt', 14:'PartEta', 15:'PartPhi', 16:'PartIsPrimary', 17:'PartPID']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_loop(epoch, dataloader, model, loss_fn, optimizer, device=\"cpu\"):\n",
    "    size = len(dataloader.dataset)\n",
    "    running_loss = 0.0\n",
    "    epoch_steps = 0\n",
    "    #for batch, data in enumerate(dataloader):\n",
    "        #ClN, Cl, ClE, ClPt, ClModNum, ClRow, ClCol, ClM02, ClM20, ClDist, PartPID = data[0], data[1],\\\n",
    "        #data[4], data[5], data[6], \\\n",
    "        #data[7], data[8], data[9], data[10], \\\n",
    "        #data[11], data[17]\n",
    "        \n",
    "        # reconstruct clusters from data\n",
    "        #clusters_e = []\n",
    "\n",
    "        #for i in range(ClN.shape[0]):\n",
    "        #    cluster_e = reconstruct_cluster(ClN[i], ClModNum[i], ClRow[i], ClCol[i], Cl[i])\n",
    "        #    clusters_e.append(cluster_e)\n",
    "        \n",
    "        #clusters_e = torch.stack(clusters_e)\n",
    "        #clusters_e = clusters_e.view(-1, 1, 20,20)\n",
    "        \n",
    "        #if INSTANCE_NOISE:\n",
    "        #    clusters_e = add_instance_noise(clusters_e)\n",
    "            \n",
    "        #clusters_e.to(device)\n",
    "        \n",
    "        #ClusterProperties = torch.cat([ClE, ClPt, ClM02, ClM20, ClDist], dim=1)\n",
    "    for batch, im, features, labels in enumerate(dataloader):\n",
    "        Clusters = im.to(device)\n",
    "        ClusterProperties = torch.cat([features[\"ClusterE\"], features[\"ClusterPt\"], features[\"ClusterM02\"]\n",
    "                                      , features[\"ClusterM20\"], features[\"ClusterDist\"]], dim=1)\n",
    "        \n",
    "        ClusterProperties.to(device)\n",
    "               \n",
    "        # zero parameter gradients\n",
    "        optimizer.zero_grad()\n",
    "        \n",
    "        # prediction and loss\n",
    "        pred = model(Clusters, ClusterProperties)\n",
    "        loss = loss_fn(pred, labels[\"PartPID\"][:,0].long())\n",
    "        \n",
    "        # Backpropagation\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        running_loss += loss.item()\n",
    "        epoch_steps += 1\n",
    "        \n",
    "        if batch % 10 == 9:\n",
    "            print(\"[%d, %5d] loss: %.3f\" % (epoch + 1, batch + 1,\n",
    "                                            running_loss / epoch_steps))\n",
    "            running_loss = 0.0        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "def val_loop(epoch, dataloader, model, loss_fn, optimizer, device=\"cpu\"):\n",
    "    val_loss = 0.0\n",
    "    val_steps = 0\n",
    "    total = 0\n",
    "    correct = 0\n",
    "    size = len(dataloader.dataset)\n",
    "    \n",
    "    #for batch, data in enumerate(dataloader):\n",
    "    #    with torch.no_grad():\n",
    "    #        ClN, Cl, ClE, ClPt, ClModNum, ClRow, ClCol, ClM02, ClM20, ClDist, PartPID = data[0], data[1],\\\n",
    "    #        data[4], data[5], data[6], \\\n",
    "    #        data[7], data[8], data[9], data[10], \\\n",
    "    #        data[11], data[17]\n",
    "        \n",
    "            # reconstruct clusters from data\n",
    "     #        clusters_e = []\n",
    "\n",
    "     #       for i in range(ClN.shape[0]):\n",
    "     #           cluster_e = reconstruct_cluster(ClN[i], ClModNum[i], ClRow[i], ClCol[i], Cl[i])\n",
    "     #           clusters_e.append(cluster_e)\n",
    "        \n",
    "     #       clusters_e = torch.stack(clusters_e)\n",
    "     #       clusters_e = clusters_e.view(-1, 1, 20,20)\n",
    "     #       if INSTANCE_NOISE:\n",
    "     #           clusters_e = add_instance_noise(clusters_e)\n",
    "     #       clusters_e.to(device)\n",
    "        \n",
    "     #       ClusterProperties = torch.cat([ClE, ClPt, ClM02, ClM20, ClDist], dim=1)\n",
    "     #       ClusterProperties.to(device)\n",
    "    \n",
    "    for batch, im, features, labels in enumerate(dataloader):\n",
    "        with torch.no_grad():\n",
    "            Clusters = im.to(device)\n",
    "            ClusterProperties = torch.cat([features[\"ClusterE\"], features[\"ClusterPt\"], features[\"ClusterM02\"]\n",
    "                                      , features[\"ClusterM20\"], features[\"ClusterDist\"]], dim=1)\n",
    "        \n",
    "            \n",
    "            ClusterProperties.to(device)\n",
    "            \n",
    "            pred = model(Clusters, ClusterProperties)\n",
    "            correct += (pred.argmax(1) == labels[\"PartPID\"][:,0]).type(torch.float).sum().item()\n",
    "\n",
    "            loss = loss_fn(pred, labels[\"PartPID\"][:,0].long())#.item()\n",
    "            val_loss += loss.cpu().numpy()\n",
    "            val_steps += 1\n",
    "    \n",
    "    with tune.checkpoint_dir(epoch) as checkpoint_dir:\n",
    "        path = os.path.join(checkpoint_dir, \"checkpoint\")\n",
    "        torch.save((model.state_dict(), optimizer.state_dict()), path)\n",
    "        \n",
    "    tune.report(loss=(val_loss / val_steps), accuracy= correct / size)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Implement training routine"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_model(config, checkpoint_dir=None):\n",
    "    \n",
    "    # load model\n",
    "    model = CNN(config[\"l1\"],config[\"l2\"],config[\"l3\"])\n",
    "    \n",
    "    # check for avlaible resource and initialize device\n",
    "    device = \"cpu\"\n",
    "    if torch.cuda.is_available():\n",
    "        device = \"cuda:0\"\n",
    "        if torch.cuda.device_count() > 1:\n",
    "            model = nn.DataParallel(model)\n",
    "    # send model to device\n",
    "    model.to(device)\n",
    "    \n",
    "    # initialise loss function and opptimizer\n",
    "    loss_fn = F.cross_entropy\n",
    "    optimizer = torch.optim.Adam(model.parameters(),lr=config[\"lr\"])\n",
    "    \n",
    "    # check whether checkpoint is available\n",
    "    if checkpoint_dir:\n",
    "        model_state, optimizer_state = torch.load(\n",
    "            os.path.join(checkpoint_dir, \"checkpoint\"))\n",
    "        model.load_state_dict(model_state)\n",
    "        optimizer.load_state_dict(optimizer_state)\n",
    "        \n",
    "    # load dataset\n",
    "    dataset_train = load_data_train()\n",
    "    \n",
    "    # split trainset in train and validation subsets\n",
    "    test_abs = int(len(dataset_train) * 0.8)\n",
    "    subset_train, subset_val = utils.random_split(\n",
    "        dataset_train, [test_abs, len(dataset_train) - test_abs])\n",
    "    \n",
    "    # get dataloaders \n",
    "    dataloader_train, dataloader_val = get_dataloader(subset_train, subset_val, int(config[\"batch_size\"]))\n",
    "                                                      \n",
    "    for epoch in range(100):\n",
    "        train_loop(epoch, dataloader_train, model, loss_fn, optimizer, device=device)\n",
    "        val_loop(epoch, dataloader_train, model, loss_fn, optimizer, device=device)                                              \n",
    "    \n",
    "    print(\"Finished Training\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Implement method for accuracy testing on test set"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "def test_accuracy(model, device=\"cpu\"):\n",
    "    \n",
    "    dataset_test = load_data_test()\n",
    "    \n",
    "    dataloader_test = utils.DataLoader(\n",
    "        dataset_test, batch_size=4, shuffle=False, num_workers=2)\n",
    "    \n",
    "    correct = 0\n",
    "    total = len(dataloader_test.dataset)\n",
    "    with torch.no_grad():\n",
    "        #for data in dataloader_test:\n",
    "        #    ClN, Cl, ClE, ClPt, ClModNum, ClRow, ClCol, ClM02, ClM20, ClDist, PartPID = data[0], data[1],\\\n",
    "        #    data[4], data[5], data[6], \\\n",
    "        #    data[7], data[8], data[9], data[10], \\\n",
    "        #    data[11], data[17]\n",
    "        \n",
    "            # reconstruct clusters from data\n",
    "        #    clusters_e = []\n",
    "\n",
    "        #    for i in range(ClN.shape[0]):\n",
    "        #        cluster_e = reconstruct_cluster(ClN[i], ClModNum[i], ClRow[i], ClCol[i], Cl[i])\n",
    "        #        clusters_e.append(cluster_e)\n",
    "        \n",
    "        #    clusters_e = torch.stack(clusters_e)\n",
    "        #    clusters_e = clusters_e.view(-1, 1, 20,20)\n",
    "        #    if INSTANCE_NOISE:\n",
    "        #        clusters_e = add_instance_noise(clusters_e)\n",
    "        #    clusters_e.to(device)\n",
    "        \n",
    "        #    ClusterProperties = torch.cat([ClE, ClPt, ClM02, ClM20, ClDist], dim=1)\n",
    "        #    ClusterProperties.to(device)\n",
    "        \n",
    "        for im, features, labels in dataloader:\n",
    "            clusters = im.to(device)\n",
    "            ClusterProperties = torch.cat([features[\"ClusterE\"], features[\"ClusterPt\"], features[\"ClusterM02\"]\n",
    "                                      , features[\"ClusterM20\"], features[\"ClusterDist\"]], dim=1)\n",
    "        \n",
    "            \n",
    "            ClusterProperties.to(device)\n",
    "            \n",
    "            \n",
    "            pred = model(clusters, ClusterProperties)\n",
    "            correct += (pred.argmax(1) == labels[\"PartPID\"][:,0]).type(torch.float).sum().item()\n",
    "\n",
    "    return correct / total"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Setup all Ray Tune functionality and start training"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "def main(num_samples=10, max_num_epochs=10, gpus_per_trial=1):\n",
    "    \n",
    "    config = {\n",
    "        \"l1\": tune.sample_from(lambda _: 2 ** np.random.randint(2, 10)),\n",
    "        \"l2\": tune.sample_from(lambda _: 2 ** np.random.randint(2, 10)),\n",
    "        \"l3\": tune.sample_from(lambda _: 2 ** np.random.randint(2, 10)),\n",
    "        \"lr\": tune.loguniform(1e-4, 1e-1),\n",
    "        \"batch_size\": tune.choice([2, 4, 8, 16, 32, 64])\n",
    "    }\n",
    "\n",
    "    scheduler = ASHAScheduler(\n",
    "        metric=\"loss\",\n",
    "        mode=\"min\",\n",
    "        max_t=max_num_epochs,\n",
    "        grace_period=1,\n",
    "        reduction_factor=2)\n",
    "    \n",
    "    reporter = CLIReporter(\n",
    "        parameter_columns=[\"l1\", \"l2\", \"l3\", \"lr\", \"batch_size\"],\n",
    "        metric_columns=[\"loss\", \"accuracy\", \"training_iteration\"])\n",
    "    \n",
    "    #Get Current date and time\n",
    "    timestr = time.strftime(\"%Y_%m_%d-%H:%M:%S\")\n",
    "    name = \"ASHA-\" + timestr\n",
    "    \n",
    "    result = tune.run(\n",
    "        partial(train_model),\n",
    "        name = name,\n",
    "        resources_per_trial={\"cpu\": cpus_per_trial, \"gpu\": gpus_per_trial},\n",
    "        config=config,\n",
    "        num_samples=num_samples,\n",
    "        local_dir = \"./Ray_Results\",\n",
    "        scheduler=scheduler,\n",
    "        progress_reporter=reporter)\n",
    "    \n",
    "    best_trial = result.get_best_trial(\"loss\", \"min\", \"last\")\n",
    "    print(\"Best trial config: {}\".format(best_trial.config))\n",
    "    print(\"Best trial final validation loss: {}\".format(best_trial.last_result[\"loss\"]))\n",
    "    print(\"Best trial final validation accuracy: {}\".format(best_trial.last_result[\"accuracy\"]))\n",
    "    \n",
    "    best_trained_model = CNN(best_trial.config[\"l1\"], best_trial.config[\"l2\"], best_trial.config[\"l3\"])\n",
    "    device = \"cpu\"\n",
    "    if torch.cuda.is_available():\n",
    "        device = \"cuda:0\"\n",
    "        if gpus_per_trial > 1:\n",
    "            best_trained_model = nn.DataParallel(best_trained_model)\n",
    "    best_trained_model.to(device)\n",
    "    \n",
    "    best_checkpoint_dir = best_trial.checkpoint.value\n",
    "    model_state, optimizer_state = torch.load(os.path.join(\n",
    "        best_checkpoint_dir, \"checkpoint\"))\n",
    "    best_trained_model.load_state_dict(model_state)\n",
    "    \n",
    "    test_acc = test_accuracy(best_trained_model, device)\n",
    "    print(\"Best trial test set accuracy: {}\".format(test_acc))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-09-16 17:17:28,208\tWARNING experiment.py:295 -- No name detected on trainable. Using DEFAULT.\n",
      "2021-09-16 17:17:28,209\tINFO registry.py:66 -- Detected unknown callable for trainable. Converting to class.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "== Status ==\n",
      "Memory usage on this node: 4.0/15.1 GiB\n",
      "Using AsyncHyperBand: num_stopped=0\n",
      "Bracket: Iter 8.000: None | Iter 4.000: None | Iter 2.000: None | Iter 1.000: None\n",
      "Resources requested: 0/12 CPUs, 0/0 GPUs, 0.0/6.98 GiB heap, 0.0/3.49 GiB objects\n",
      "Result logdir: /home/jhonerma/ML-Notebooks/CNN/Ray_Results/ASHA-2021_09_16-17:17:28\n",
      "Number of trials: 10/10 (10 PENDING)\n",
      "+---------------------+----------+-------+------+------+------+-------------+--------------+\n",
      "| Trial name          | status   | loc   |   l1 |   l2 |   l3 |          lr |   batch_size |\n",
      "|---------------------+----------+-------+------+------+------+-------------+--------------|\n",
      "| DEFAULT_34584_00000 | PENDING  |       |  128 |   16 |   64 | 0.0900838   |           32 |\n",
      "| DEFAULT_34584_00001 | PENDING  |       |  512 |    8 |   32 | 0.0301651   |            4 |\n",
      "| DEFAULT_34584_00002 | PENDING  |       |   16 |  512 |  256 | 0.00774179  |           64 |\n",
      "| DEFAULT_34584_00003 | PENDING  |       |   32 |    8 |  128 | 0.000749776 |            8 |\n",
      "| DEFAULT_34584_00004 | PENDING  |       |  512 |   32 |    4 | 0.0526818   |            8 |\n",
      "| DEFAULT_34584_00005 | PENDING  |       |   16 |  256 |  128 | 0.000129381 |           64 |\n",
      "| DEFAULT_34584_00006 | PENDING  |       |  512 |  256 |   32 | 0.000101087 |           64 |\n",
      "| DEFAULT_34584_00007 | PENDING  |       |   32 |  512 |  256 | 0.00271265  |           64 |\n",
      "| DEFAULT_34584_00008 | PENDING  |       |   64 |   64 |  256 | 0.000439365 |            4 |\n",
      "| DEFAULT_34584_00009 | PENDING  |       |    8 |    8 |   16 | 0.0812625   |           64 |\n",
      "+---------------------+----------+-------+------+------+------+-------------+--------------+\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m 2021-09-16 17:17:29,828\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20360)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "2021-09-16 17:17:29,933\tERROR trial_runner.py:773 -- Trial DEFAULT_34584_00000: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20360, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7fbeece9bcd0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20360, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7fbeece9bcd0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "  File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m 2021-09-16 17:17:29,982\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20366)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m 2021-09-16 17:17:30,059\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20364)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m 2021-09-16 17:17:29,981\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20363)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m 2021-09-16 17:17:30,032\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20359)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-09-16 17:17:30,091\tERROR trial_runner.py:773 -- Trial DEFAULT_34584_00001: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20366, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7fc9df0acca0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20366, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7fc9df0acca0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "  File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "ValueError: not enough values to unpack (expected 4, got 2)\n",
      "2021-09-16 17:17:30,101\tERROR trial_runner.py:773 -- Trial DEFAULT_34584_00003: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20363, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7f4fdd769ca0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20363, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7f4fdd769ca0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "  File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "ValueError: not enough values to unpack (expected 4, got 2)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for DEFAULT_34584_00000:\n",
      "  {}\n",
      "  \n",
      "Result for DEFAULT_34584_00001:\n",
      "  {}\n",
      "  \n",
      "Result for DEFAULT_34584_00003:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-09-16 17:17:30,153\tERROR trial_runner.py:773 -- Trial DEFAULT_34584_00004: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20364, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7f1801869ca0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20364, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7f1801869ca0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "  File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "ValueError: not enough values to unpack (expected 4, got 2)\n",
      "2021-09-16 17:17:30,158\tERROR trial_runner.py:773 -- Trial DEFAULT_34584_00008: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20359, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7ff1be11ecd0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20359, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7ff1be11ecd0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "  File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "ValueError: not enough values to unpack (expected 4, got 2)\n",
      "2021-09-16 17:17:30,164\tERROR trial_runner.py:773 -- Trial DEFAULT_34584_00002: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20365, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7f380c3e5cd0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20365, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7f380c3e5cd0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "  File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m 2021-09-16 17:17:30,108\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20362)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m 2021-09-16 17:17:30,076\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20365)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m 2021-09-16 17:17:30,131\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20361)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m 2021-09-16 17:17:30,103\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20357)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m 2021-09-16 17:17:30,128\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/threading.py\", line 973, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m   File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m   File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m   File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "\u001b[2m\u001b[36m(pid=20358)\u001b[0m ValueError: not enough values to unpack (expected 4, got 2)\n",
      "2021-09-16 17:17:30,186\tERROR trial_runner.py:773 -- Trial DEFAULT_34584_00007: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20357, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7f059831fcd0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20357, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7f059831fcd0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "  File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "ValueError: not enough values to unpack (expected 4, got 2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-09-16 17:17:30,199\tERROR trial_runner.py:773 -- Trial DEFAULT_34584_00009: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20362, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7fceef52cca0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20362, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7fceef52cca0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "  File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "ValueError: not enough values to unpack (expected 4, got 2)\n",
      "2021-09-16 17:17:30,210\tERROR trial_runner.py:773 -- Trial DEFAULT_34584_00006: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20358, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7f2af1b4acd0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20358, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7f2af1b4acd0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "  File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "ValueError: not enough values to unpack (expected 4, got 2)\n",
      "2021-09-16 17:17:30,224\tERROR trial_runner.py:773 -- Trial DEFAULT_34584_00005: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20361, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7fbc9a08eca0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=20361, ip=10.67.95.37, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7fbc9a08eca0>)\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"/home/jhonerma/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"/tmp/ipykernel_19636/3286269760.py\", line 38, in train_model\n",
      "  File \"/tmp/ipykernel_19636/424599286.py\", line 27, in train_loop\n",
      "ValueError: not enough values to unpack (expected 4, got 2)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for DEFAULT_34584_00004:\n",
      "  {}\n",
      "  \n",
      "Result for DEFAULT_34584_00008:\n",
      "  {}\n",
      "  \n",
      "Result for DEFAULT_34584_00002:\n",
      "  {}\n",
      "  \n",
      "Result for DEFAULT_34584_00007:\n",
      "  {}\n",
      "  \n",
      "Result for DEFAULT_34584_00009:\n",
      "  {}\n",
      "  \n",
      "Result for DEFAULT_34584_00006:\n",
      "  {}\n",
      "  \n",
      "Result for DEFAULT_34584_00005:\n",
      "  {}\n",
      "  \n",
      "== Status ==\n",
      "Memory usage on this node: 4.0/15.1 GiB\n",
      "Using AsyncHyperBand: num_stopped=0\n",
      "Bracket: Iter 8.000: None | Iter 4.000: None | Iter 2.000: None | Iter 1.000: None\n",
      "Resources requested: 0/12 CPUs, 0/0 GPUs, 0.0/6.98 GiB heap, 0.0/3.49 GiB objects\n",
      "Result logdir: /home/jhonerma/ML-Notebooks/CNN/Ray_Results/ASHA-2021_09_16-17:17:28\n",
      "Number of trials: 10/10 (10 ERROR)\n",
      "+---------------------+----------+-------+------+------+------+-------------+--------------+\n",
      "| Trial name          | status   | loc   |   l1 |   l2 |   l3 |          lr |   batch_size |\n",
      "|---------------------+----------+-------+------+------+------+-------------+--------------|\n",
      "| DEFAULT_34584_00000 | ERROR    |       |  128 |   16 |   64 | 0.0900838   |           32 |\n",
      "| DEFAULT_34584_00001 | ERROR    |       |  512 |    8 |   32 | 0.0301651   |            4 |\n",
      "| DEFAULT_34584_00002 | ERROR    |       |   16 |  512 |  256 | 0.00774179  |           64 |\n",
      "| DEFAULT_34584_00003 | ERROR    |       |   32 |    8 |  128 | 0.000749776 |            8 |\n",
      "| DEFAULT_34584_00004 | ERROR    |       |  512 |   32 |    4 | 0.0526818   |            8 |\n",
      "| DEFAULT_34584_00005 | ERROR    |       |   16 |  256 |  128 | 0.000129381 |           64 |\n",
      "| DEFAULT_34584_00006 | ERROR    |       |  512 |  256 |   32 | 0.000101087 |           64 |\n",
      "| DEFAULT_34584_00007 | ERROR    |       |   32 |  512 |  256 | 0.00271265  |           64 |\n",
      "| DEFAULT_34584_00008 | ERROR    |       |   64 |   64 |  256 | 0.000439365 |            4 |\n",
      "| DEFAULT_34584_00009 | ERROR    |       |    8 |    8 |   16 | 0.0812625   |           64 |\n",
      "+---------------------+----------+-------+------+------+------+-------------+--------------+\n",
      "Number of errored trials: 10\n",
      "+---------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n",
      "| Trial name          |   # failures | error file                                                                                                                                                               |\n",
      "|---------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n",
      "| DEFAULT_34584_00000 |            1 | /home/jhonerma/ML-Notebooks/CNN/Ray_Results/ASHA-2021_09_16-17:17:28/DEFAULT_34584_00000_0_batch_size=32,l1=128,l2=16,l3=64,lr=0.090084_2021-09-16_17-17-28/error.txt    |\n",
      "| DEFAULT_34584_00001 |            1 | /home/jhonerma/ML-Notebooks/CNN/Ray_Results/ASHA-2021_09_16-17:17:28/DEFAULT_34584_00001_1_batch_size=4,l1=512,l2=8,l3=32,lr=0.030165_2021-09-16_17-17-28/error.txt      |\n",
      "| DEFAULT_34584_00002 |            1 | /home/jhonerma/ML-Notebooks/CNN/Ray_Results/ASHA-2021_09_16-17:17:28/DEFAULT_34584_00002_2_batch_size=64,l1=16,l2=512,l3=256,lr=0.0077418_2021-09-16_17-17-28/error.txt  |\n",
      "| DEFAULT_34584_00003 |            1 | /home/jhonerma/ML-Notebooks/CNN/Ray_Results/ASHA-2021_09_16-17:17:28/DEFAULT_34584_00003_3_batch_size=8,l1=32,l2=8,l3=128,lr=0.00074978_2021-09-16_17-17-28/error.txt    |\n",
      "| DEFAULT_34584_00004 |            1 | /home/jhonerma/ML-Notebooks/CNN/Ray_Results/ASHA-2021_09_16-17:17:28/DEFAULT_34584_00004_4_batch_size=8,l1=512,l2=32,l3=4,lr=0.052682_2021-09-16_17-17-28/error.txt      |\n",
      "| DEFAULT_34584_00005 |            1 | /home/jhonerma/ML-Notebooks/CNN/Ray_Results/ASHA-2021_09_16-17:17:28/DEFAULT_34584_00005_5_batch_size=64,l1=16,l2=256,l3=128,lr=0.00012938_2021-09-16_17-17-28/error.txt |\n",
      "| DEFAULT_34584_00006 |            1 | /home/jhonerma/ML-Notebooks/CNN/Ray_Results/ASHA-2021_09_16-17:17:28/DEFAULT_34584_00006_6_batch_size=64,l1=512,l2=256,l3=32,lr=0.00010109_2021-09-16_17-17-28/error.txt |\n",
      "| DEFAULT_34584_00007 |            1 | /home/jhonerma/ML-Notebooks/CNN/Ray_Results/ASHA-2021_09_16-17:17:28/DEFAULT_34584_00007_7_batch_size=64,l1=32,l2=512,l3=256,lr=0.0027127_2021-09-16_17-17-28/error.txt  |\n",
      "| DEFAULT_34584_00008 |            1 | /home/jhonerma/ML-Notebooks/CNN/Ray_Results/ASHA-2021_09_16-17:17:28/DEFAULT_34584_00008_8_batch_size=4,l1=64,l2=64,l3=256,lr=0.00043937_2021-09-16_17-17-29/error.txt   |\n",
      "| DEFAULT_34584_00009 |            1 | /home/jhonerma/ML-Notebooks/CNN/Ray_Results/ASHA-2021_09_16-17:17:28/DEFAULT_34584_00009_9_batch_size=64,l1=8,l2=8,l3=16,lr=0.081262_2021-09-16_17-17-29/error.txt       |\n",
      "+---------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n",
      "\n"
     ]
    },
    {
     "ename": "TuneError",
     "evalue": "('Trials did not complete', [DEFAULT_34584_00000, DEFAULT_34584_00001, DEFAULT_34584_00002, DEFAULT_34584_00003, DEFAULT_34584_00004, DEFAULT_34584_00005, DEFAULT_34584_00006, DEFAULT_34584_00007, DEFAULT_34584_00008, DEFAULT_34584_00009])",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTuneError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_19636/3778046435.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mmain\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnum_samples\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m10\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmax_num_epochs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m10\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mgpus_per_trial\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mgpus_per_trial\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/tmp/ipykernel_19636/1425197422.py\u001b[0m in \u001b[0;36mmain\u001b[0;34m(num_samples, max_num_epochs, gpus_per_trial)\u001b[0m\n\u001b[1;32m     24\u001b[0m     \u001b[0mname\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m\"ASHA-\"\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mtimestr\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     25\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 26\u001b[0;31m     result = tune.run(\n\u001b[0m\u001b[1;32m     27\u001b[0m         \u001b[0mpartial\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtrain_model\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     28\u001b[0m         \u001b[0mname\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/cnn-env/lib/python3.9/site-packages/ray/tune/tune.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, loggers, ray_auto_init, run_errored_only, global_checkpoint_period, with_server, upload_dir, sync_to_cloud, sync_to_driver, sync_on_checkpoint, _remote)\u001b[0m\n\u001b[1;32m    553\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    554\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mraise_on_failed_trial\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mstate\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0msignal\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSIGINT\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 555\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mTuneError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    556\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    557\u001b[0m             \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete: %s\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTuneError\u001b[0m: ('Trials did not complete', [DEFAULT_34584_00000, DEFAULT_34584_00001, DEFAULT_34584_00002, DEFAULT_34584_00003, DEFAULT_34584_00004, DEFAULT_34584_00005, DEFAULT_34584_00006, DEFAULT_34584_00007, DEFAULT_34584_00008, DEFAULT_34584_00009])"
     ]
    }
   ],
   "source": [
    "main(num_samples=10, max_num_epochs=10, gpus_per_trial=gpus_per_trial)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:cnn-env]",
   "language": "python",
   "name": "conda-env-cnn-env-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
